name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          cache: gradle
      - name: gradle execute permission
        run: chmod +x gradlew
      - name: gradle build
        run: ./gradlew build
      - name: gradle test
        run: ./gradlew test